name: Terraform bild and deploy
# This workflow builds and deploys Terraform configurations

on:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      actions: write
      deployments: write
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (Access Key)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform import
        run: |
          terraform import aws_vpc.eks-vpc vpc-0031c2d4baf4fae26
          terraform import aws_iam_role.eks-cluster-role eks-cluster-example
          terraform import aws_iam_role.fargate-pf-role eks-fargate-profile-role
          terraform import aws_iam_role.eks-ng-role eks-node-group-role
          terraform import aws_eks_cluster.eks-cluster eks-cluster

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply --auto-approve
